services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: trello_db
      POSTGRES_PASSWORD: trello_db
      POSTGRES_DB: trello_db
    ports:
      - "4444:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
